name: CI/CD Pipelines
on:
    push:
        branches: [ main ]
jobs:
  CI:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: 18.6.0
      - run: npm install
      - run: npm run build --if-present
  CD:
    runs-on: Ubuntu-20.04
    needs: [CI]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name donghakang-app \
            --deployment-group-name Prod \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}